=== xFran1/SimulacroExamenLMDanzas/SimulacroExamenLMDanzas/Examen de Lenguaje de Marcas - SIMULACRO - 8-3-2024/danzas.dtd
<!ELEMENT danzas (danza+)>
<!ELEMENT danza (nombre,regionDeOrigen,descripcion,numPersonas,tipoDeMusica,particularidades)>
<!ATTLIST danza id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT regionDeOrigen (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numPersonas (#PCDATA)>
<!ELEMENT tipoDeMusica (#PCDATA)>
<!ELEMENT particularidades (#PCDATA)>

=== xFran1/SimulacroExamenLMDanzas/SimulacroExamenLMDanzas/Examen de Lenguaje de Marcas - SIMULACRO - 8-3-2024/danzas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE danzas SYSTEM "danzas.dtd">

<danzas>

    <danza id="1">
        <nombre>Samba</nombre>
        <regionDeOrigen>Brasil</regionDeOrigen>
        <descripcion>La samba es un género musical y danza originarios de Brasil. Es una expresión cultural que combina elementos africanos y europeos.</descripcion>
        <numPersonas>Varía, desde parejas hasta grandes grupos de bailarines</numPersonas>
        <tipoDeMusica>Percusión y ritmos contagiosos</tipoDeMusica>
        <particularidades>Destaca por sus movimientos rápidos de cadera y piernas.</particularidades>
    </danza>
    
    <danza id="2">
        <nombre>Ballet</nombre>
        <regionDeOrigen>Europa (principalmente Francia e Italia)</regionDeOrigen>
        <descripcion>El ballet es un estilo de danza que se originó durante el Renacimiento en Italia y se desarrolló más plenamente en Francia durante el siglo XVII.</descripcion>
        <numPersonas>Depende de la obra, desde solos hasta grandes compañías de ballet</numPersonas>
        <tipoDeMusica>Clásica</tipoDeMusica>
        <particularidades>Caracterizado por movimientos elegantes, gráciles y precisos.</particularidades>
    </danza>
    
    <danza id="3">
        <nombre>Hula</nombre>
        <regionDeOrigen>Hawái</regionDeOrigen>
        <descripcion>El hula es una forma de danza tradicional hawaiana acompañada de cánticos o canciones. Es una forma de contar historias y transmitir conocimientos.</descripcion>
        <numPersonas>Varía, desde solistas hasta grupos</numPersonas>
        <tipoDeMusica>Instrumentos de percusión y canto</tipoDeMusica>
        <particularidades>Incluye movimientos fluidos de manos y caderas, a menudo acompañados de implementos tradicionales como el ipu (calabaza) o el ili'ili (piedras pequeñas).</particularidades>
    </danza>
    
    <danza id="4">
        <nombre>Flamenco</nombre>
        <regionDeOrigen>Andalucía, España</regionDeOrigen>
        <descripcion>El flamenco es un arte que incluye cante, toque, baile, jaleo y palmas. Se originó en el sur de España en el siglo XVIII y está influenciado por diversas culturas, incluidas la gitana, árabe y judía.</descripcion>
        <numPersonas>Principalmente solistas o parejas, aunque también pueden haber grupos de bailarines y músicos</numPersonas>
        <tipoDeMusica>Guitarra flamenca y cante flamenco</tipoDeMusica>
        <particularidades>Se caracteriza por la pasión, la improvisación y los movimientos vigorosos.</particularidades>
    </danza>
    
    <danza id="5">
        <nombre>Kathak</nombre>
        <regionDeOrigen>India</regionDeOrigen>
        <descripcion>El kathak es una de las formas principales de danza clásica india. Se originó en el norte de la India y se ha desarrollado a lo largo de siglos, incorporando elementos de la música y la narrativa indias.</descripcion>
        <numPersonas>Principalmente solistas o parejas, aunque también pueden haber grupos de bailarines</numPersonas>
        <tipoDeMusica>Música clásica india, incluyendo tabla y sitar</tipoDeMusica>
        <particularidades>Destaca por sus intrincados movimientos de pies, gestos faciales expresivos y el uso de ghungroo (cascabeles) en los tobillos.</particularidades>
    </danza>

</danzas>
